import { useEffect, useMemo, useState } from 'react';
import { Activity, CalendarClock, Cpu, House, Monitor, Plus, QrCode, RefreshCw, ShieldCheck, Wrench } from 'lucide-react';
import QRCode from 'qrcode';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { useTickets } from '../hooks/useTickets';
import { addAssetEntity, createAsset, createMaintenancePlan, getHomeAssistantStates, getOperationsData } from '../lib/operations';
import type { Asset, AssetEntity, HomeAssistantState, MaintenancePlan } from '../types/database';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { isTicketOpen } from '../utils/tickets';

const inputClass = 'w-full rounded-2xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 outline-none focus:border-sky-400 dark:border-slate-700 dark:bg-slate-950 dark:text-white';

export function SmartHomePage() {
  const { pathname } = useLocation();
  const mode = pathname.split('/').pop() ?? 'assets';
  const { profile, isAdmin } = useAuth();
  const { tickets } = useTickets();
  const [assets, setAssets] = useState<Asset[]>([]); const [entities, setEntities] = useState<AssetEntity[]>([]); const [plans, setPlans] = useState<MaintenancePlan[]>([]);
  const [states, setStates] = useState<HomeAssistantState[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [showCreate, setShowCreate] = useState(false);
  const [assetForm, setAssetForm] = useState({ name: '', area: 'Wohnzimmer', category: 'Geräte', manufacturer: '', model: '', entityId: '' });
  const [planForm, setPlanForm] = useState({ title: '', assetId: '', frequency: 'monthly' as MaintenancePlan['frequency'], nextDue: new Date(Date.now() + 86400000).toISOString().slice(0, 16) });
  async function load() { setBusy(true); setError(''); try { const data = await getOperationsData(); setAssets(data.assets); setEntities(data.entities); setPlans(data.maintenance); try { setStates(await getHomeAssistantStates()); } catch { /* HA may intentionally be unavailable */ } } catch (cause) { setError(cause instanceof Error ? cause.message : 'Daten konnten nicht geladen werden.'); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  const stateMap = useMemo(() => new Map(states.map((state) => [state.entity_id, state])), [states]);
  const openByAsset = (id: string) => tickets.filter((ticket) => ticket.asset_id === id && isTicketOpen(ticket)).length;
  const assetHealth = (asset: Asset) => { if (asset.health_override != null) return asset.health_override; const linked = entities.filter((item) => item.asset_id === asset.id); const offline = linked.filter((item) => ['unavailable', 'unknown'].includes(stateMap.get(item.entity_id)?.state ?? '')).length; return Math.max(0, 100 - openByAsset(asset.id) * 12 - offline * 25); };
  const overall = assets.length ? Math.round(assets.reduce((sum, asset) => sum + assetHealth(asset), 0) / assets.length) : 100;
  async function submitAsset(event: React.FormEvent) { event.preventDefault(); if (!profile) return; setBusy(true); try { const asset = await createAsset({ name: assetForm.name, area: assetForm.area, category: assetForm.category, manufacturer: assetForm.manufacturer || null, model: assetForm.model || null, created_by: profile.id }); if (assetForm.entityId) await addAssetEntity(asset.id, assetForm.entityId); setAssetForm({ ...assetForm, name: '', manufacturer: '', model: '', entityId: '' }); setShowCreate(false); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Gerät konnte nicht gespeichert werden.'); } finally { setBusy(false); } }
  async function submitPlan(event: React.FormEvent) { event.preventDefault(); if (!profile) return; setBusy(true); try { await createMaintenancePlan({ asset_id: planForm.assetId || null, title: planForm.title, description: null, frequency: planForm.frequency, interval_count: 1, next_due_at: new Date(planForm.nextDue).toISOString(), active: true, auto_create_ticket: true, created_by: profile.id }); setPlanForm({ ...planForm, title: '' }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Plan konnte nicht gespeichert werden.'); } finally { setBusy(false); } }

  if (mode === 'display') return <Wallboard assets={assets} plans={plans} overall={overall} openTickets={tickets.filter(isTicketOpen).length} />;
  return <div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
    <header className="overflow-hidden rounded-[32px] bg-gradient-to-br from-slate-950 via-sky-950 to-cyan-900 p-6 text-white shadow-xl">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Home Operations</p><h1 className="mt-2 text-3xl font-black">{mode === 'health' ? 'Home Health' : mode === 'maintenance' ? 'Wartungszentrale' : mode === 'rooms' ? 'Räume & Live-Zustände' : 'Geräte & Assets'}</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Geräteakten, Home-Assistant-Livestatus, Wartung und Tickets an einem Ort.</p></div><Button variant="secondary" onClick={() => void load()} disabled={busy}><RefreshCw size={16} className={busy ? 'animate-spin' : ''}/>Aktualisieren</Button></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-4"><Metric label="Home Score" value={`${overall}%`} icon={Activity}/><Metric label="Assets" value={String(assets.length)} icon={Cpu}/><Metric label="HA Entitäten" value={String(states.length)} icon={House}/><Metric label="Wartungen" value={String(plans.filter((p) => p.active).length)} icon={Wrench}/></div>
    </header>
    {error && <div className="rounded-2xl bg-red-50 p-3 text-sm font-semibold text-red-700 dark:bg-red-950/40 dark:text-red-300">{error}</div>}
    <nav className="flex gap-2 overflow-x-auto"><Tab to="/app/assets" label="Assets" icon={Cpu}/><Tab to="/app/health" label="Health" icon={Activity}/><Tab to="/app/maintenance" label="Wartung" icon={CalendarClock}/><Tab to="/app/rooms" label="Räume" icon={House}/><Tab to="/app/display" label="Wallboard" icon={Monitor}/></nav>
    {mode === 'maintenance' ? <MaintenanceView plans={plans} assets={assets} isAdmin={isAdmin} form={planForm} setForm={setPlanForm} submit={submitPlan}/> : mode === 'rooms' ? <RoomsView assets={assets} entities={entities} states={stateMap}/> : <AssetView assets={assets} entities={entities} states={stateMap} health={assetHealth} showCreate={showCreate} setShowCreate={setShowCreate} form={assetForm} setForm={setAssetForm} submit={submitAsset} isAdmin={isAdmin} healthMode={mode === 'health'}/>} 
  </div>;
}

function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Activity }) { return <div className="rounded-2xl bg-white/10 p-3 backdrop-blur"><Icon size={17} className="text-cyan-300"/><p className="mt-2 text-2xl font-black">{value}</p><p className="text-xs text-slate-300">{label}</p></div>; }
function Tab({ to, label, icon: Icon }: { to: string; label: string; icon: typeof Activity }) { return <Link to={to} className="flex shrink-0 items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200"><Icon size={16}/>{label}</Link>; }
function AssetView({ assets, entities, states, health, showCreate, setShowCreate, form, setForm, submit, isAdmin, healthMode }: any) { return <><div className="flex justify-end">{isAdmin && <Button onClick={() => setShowCreate(!showCreate)}><Plus size={16}/>Asset erfassen</Button>}</div>{showCreate && <Card className="p-5"><form onSubmit={submit} className="grid gap-3 md:grid-cols-3"><input className={inputClass} required placeholder="Gerätename" value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/><input className={inputClass} placeholder="Raum" value={form.area} onChange={(e) => setForm({...form,area:e.target.value})}/><input className={inputClass} placeholder="Kategorie" value={form.category} onChange={(e) => setForm({...form,category:e.target.value})}/><input className={inputClass} placeholder="Hersteller" value={form.manufacturer} onChange={(e) => setForm({...form,manufacturer:e.target.value})}/><input className={inputClass} placeholder="Modell" value={form.model} onChange={(e) => setForm({...form,model:e.target.value})}/><input className={inputClass} placeholder="HA Entity, z. B. sensor.heizung" value={form.entityId} onChange={(e) => setForm({...form,entityId:e.target.value})}/><Button type="submit">Speichern</Button></form></Card>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{assets.map((asset: Asset) => <AssetCard key={asset.id} asset={asset} entities={entities.filter((e: AssetEntity) => e.asset_id === asset.id)} states={states} health={health(asset)} healthMode={healthMode}/>)}</div>{!assets.length && <Card className="p-8 text-center text-sm text-slate-500">Noch keine Assets erfasst.</Card>}</>; }
function AssetCard({ asset, entities, states, health, healthMode }: { asset: Asset; entities: AssetEntity[]; states: Map<string,HomeAssistantState>; health: number; healthMode: boolean }) { const [qr,setQr]=useState(''); useEffect(()=>{ void QRCode.toDataURL(`${location.origin}/app/assets?asset=${asset.id}`, { width: 280, margin: 1 }).then(setQr); },[asset.id]); return <Card className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-sky-600">{asset.area} · {asset.category}</p><h2 className="mt-1 text-lg font-black text-slate-950 dark:text-white">{asset.name}</h2><p className="text-xs text-slate-500">{[asset.manufacturer,asset.model].filter(Boolean).join(' · ') || 'Keine Modelldaten'}</p></div><div className={`rounded-2xl px-3 py-2 text-lg font-black ${health >= 80 ? 'bg-emerald-50 text-emerald-600' : health >= 55 ? 'bg-amber-50 text-amber-600' : 'bg-red-50 text-red-600'}`}>{health}</div></div><div className="mt-4 space-y-2">{entities.map((entity) => { const state=states.get(entity.entity_id); return <div key={entity.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-xs dark:bg-slate-800"><span className="truncate font-semibold">{state?.attributes.friendly_name || entity.entity_id}</span><span className={['unknown','unavailable'].includes(state?.state ?? '') ? 'text-red-500' : 'text-emerald-600'}>{state?.state ?? 'nicht geladen'} {state?.attributes.unit_of_measurement}</span></div>;})}</div>{healthMode && <p className="mt-3 text-xs text-slate-500">Score aus offenen Tickets und nicht erreichbaren Entitäten.</p>}<details className="mt-4"><summary className="flex cursor-pointer items-center gap-2 text-xs font-bold text-slate-500"><QrCode size={15}/>QR-Gerätepass</summary>{qr && <img src={qr} alt={`QR-Code für ${asset.name}`} className="mt-3 h-36 w-36 rounded-xl"/>}</details></Card>; }
function MaintenanceView({ plans, assets, isAdmin, form, setForm, submit }: any) { return <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><div className="space-y-3">{plans.map((plan: MaintenancePlan)=><Card key={plan.id} className="flex items-center gap-4 p-4"><div className="rounded-2xl bg-amber-50 p-3 text-amber-600"><Wrench size={20}/></div><div className="flex-1"><p className="font-black text-slate-900 dark:text-white">{plan.title}</p><p className="text-xs text-slate-500">{assets.find((a: Asset)=>a.id===plan.asset_id)?.name || 'Allgemein'} · {plan.frequency} · nächster Termin {new Date(plan.next_due_at).toLocaleDateString('de-DE')}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Auto-Ticket</span></Card>)}</div>{isAdmin && <Card className="h-fit p-5"><h2 className="font-black">Wartungsplan anlegen</h2><form onSubmit={submit} className="mt-4 space-y-3"><input required className={inputClass} placeholder="Wartungstitel" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/><select className={inputClass} value={form.assetId} onChange={(e)=>setForm({...form,assetId:e.target.value})}><option value="">Allgemein</option>{assets.map((a: Asset)=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select className={inputClass} value={form.frequency} onChange={(e)=>setForm({...form,frequency:e.target.value})}><option value="weekly">Wöchentlich</option><option value="monthly">Monatlich</option><option value="yearly">Jährlich</option></select><input type="datetime-local" className={inputClass} value={form.nextDue} onChange={(e)=>setForm({...form,nextDue:e.target.value})}/><Button type="submit" className="w-full">Plan aktivieren</Button></form></Card>}</div>; }
function RoomsView({ assets, entities, states }: { assets: Asset[]; entities: AssetEntity[]; states: Map<string,HomeAssistantState> }) { const rooms=[...new Set(assets.map(a=>a.area))]; return <div className="grid gap-4 md:grid-cols-2">{rooms.map(room=><Card key={room} className="p-5"><h2 className="flex items-center gap-2 text-xl font-black"><House size={20} className="text-sky-500"/>{room}</h2><div className="mt-4 grid gap-2">{assets.filter(a=>a.area===room).map(asset=><div key={asset.id} className="rounded-2xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-sm font-bold">{asset.name}</p><p className="mt-1 text-xs text-slate-500">{entities.filter(e=>e.asset_id===asset.id).map(e=>`${states.get(e.entity_id)?.attributes.friendly_name || e.entity_id}: ${states.get(e.entity_id)?.state ?? '–'}`).join(' · ') || 'Keine HA-Entität'}</p></div>)}</div></Card>)}</div>; }
function Wallboard({ assets, plans, overall, openTickets }: { assets: Asset[]; plans: MaintenancePlan[]; overall: number; openTickets: number }) { return <div className="min-h-[calc(100vh-5rem)] bg-slate-950 p-6 text-white sm:p-10"><div className="mx-auto max-w-7xl"><div className="flex items-center justify-between"><div><p className="text-sm font-black uppercase tracking-[.3em] text-cyan-300">HomeDesk Live</p><h1 className="mt-2 text-4xl font-black">Guten Überblick.</h1></div><ShieldCheck size={52} className="text-emerald-400"/></div><div className="mt-10 grid gap-5 md:grid-cols-3"><BigMetric label="Home Health" value={`${overall}%`}/><BigMetric label="Offene Tickets" value={String(openTickets)}/><BigMetric label="Aktive Wartungen" value={String(plans.filter(p=>p.active).length)}/></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{assets.slice(0,8).map(asset=><div key={asset.id} className="rounded-3xl border border-white/10 bg-white/5 p-5"><p className="text-xs font-bold uppercase text-cyan-300">{asset.area}</p><p className="mt-2 text-xl font-black">{asset.name}</p><p className="mt-1 text-sm text-slate-400">{asset.category}</p></div>)}</div></div></div>; }
function BigMetric({label,value}:{label:string;value:string}) { return <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-white/10 to-white/5 p-7"><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-5xl font-black">{value}</p></div>; }
